import type { Metadata } from 'next';
import { Inter_Tight } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';
import { auth } from '@/auth';

import { Toaster } from '@/components/ui/toaster';
import StoreProvider from './StoreProvider';

import './globals.css';

const interTight = Inter_Tight({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Linques',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <StoreProvider>
        <html lang="tr">
          <body className={interTight.className}>
            {children}
            <Toaster />
          </body>
        </html>
      </StoreProvider>
    </SessionProvider>
  );
}
